apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipl-ingress
  namespace: saurav-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ipl-service
            port:
              number: 80


      - path: /netflix
        pathType: Prefix
        backend:
          service:
            name: netflix-service
            port:
              number: 81


      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 82

      - path: /httpd
        pathType: Prefix
        backend:
          service:
            name: httpd-service
            port:
              number: 83

      - path: /node
        pathType: Prefix
        backend:
          service:
            name: httpd-service
            port:
              number: 84